# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNW83wWsP_2kPNjdIYVIanjhnHcVOe0w
"""

import math
import time
import functools
import contextlib
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torch.nn.attention import sdpa_kernel, SDPBackend
import torch

def run_naive_attention(q, k, v, is_causal=True):
    with sdpa_kernel(SDPBackend.MATH):
        return F.scaled_dot_product_attention(q, k, v, is_causal=is_causal)

def run_flash_attention(q, k, v, is_causal=True):
    with sdpa_kernel(SDPBackend.FLASH_ATTENTION):
        return F.scaled_dot_product_attention(q, k, v, is_causal=is_causal)

# 1. 準備測試數據 (Shape: B, H, L, D)
# 這段程式碼主要用於生成模擬的 Attention:
# B (Batch Size): 批次大小。
# H (Num Heads): 注意力頭的數量。
# L (Sequence Length): 序列長度，即文本中 token 的數量。
# D (Head Dimension): 每個注意力頭的特徵維度。
B, H, L, D = 4, 8, 256, 64

# q, k, v: 分別代表 Query, Key 和 Value，這是計算 Attention 所需的三個基本元素。
q = torch.randn(B, H, L, D)
k = torch.randn(B, H, L, D)
v = torch.randn(B, H, L, D)

# 2. 執行不同的attention
out_naive = run_naive_attention(q, k, v)
out_flash = run_flash_attention(q, k, v)
#print(out_naive.shape)

# 3. 計算差異
diff = (out_naive - out_flash).abs().max().item()
print("最大差異：", diff)

def benchmark_attention(mode, q, k, v, warmup=1, repeats=3):
    """
    測試指定 Attention 模式的執行時間。
    mode 可以是 'naive' 或 'flash'。
    Returns: avg_latency_ms
    """

    # 1. Warmup: Run the function 10 times without timing to stabilize the GPU state.
    for _ in range(warmup):
        if mode == 'naive':
            run_naive_attention(q, k, v)
        elif mode == 'flash':
            run_flash_attention(q, k, v)

    torch.cuda.synchronize() #如果不加同步，你後面做計時或記憶體統計時，可能會不準。

    # 2. Timing
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    start_event.record() #從這裡開始算時間
    for _ in range(repeats):
        if mode == 'naive':
            run_naive_attention(q, k, v)
        elif mode == 'flash':
            run_flash_attention(q, k, v)
    end_event.record() #到這裡結束計時

    torch.cuda.synchronize() #等整个 repeats 次 attention 都真的完成，再讀時間。

    # 計算平均延遲 (毫秒)
    avg_latency_ms = start_event.elapsed_time(end_event) / repeats

    return avg_latency_ms

SEQ_LENS = [64, 128, 256, 512, 1024, 2048, 4096]
B, H, D = [4, 8, 64]

print(f"Starting Benchmarks ... Params: B={B}, H={H}, D={D}")
print( "~" * 90)
print(f"{'Seq Len':<10} | {'Naive (ms)':<12} | {'Flash (ms)':<12} | {'Flash Speedup':<15}")
print( "~" * 90)

for L in SEQ_LENS:
    # Generate random input tensors
    q = torch.randn(B, H, L, D)
    k = torch.randn(B, H, L, D)
    v = torch.randn(B, H, L, D)

    # Naive Attention
    lat_naive = benchmark_attention('naive', q, k, v)
    math_str = f"{lat_naive:.2f}"

    torch.cuda.empty_cache()

    # Flash Attention
    lat_flash = benchmark_attention('flash', q, k, v)
    flash_str = f"{lat_flash:.2f}"

    torch.cuda.empty_cache()

    # Calculate Speedup (Naive / Flash)
    speedup = "~"
    s = lat_naive / lat_flash
    speedup = f"{s:.2f}x"

    # Print progress
    print(f"{L:<10} | {math_str:<12} | {flash_str:<12} | {speedup:<15}")

print( "~" * 90)
print("Benchmark completed.")

from transformers import pipeline

model_id = "google/gemma-3-4b-it"
print(f"使用真實模型： {model_id} ...")

print("下載模型中...")
pipe_eager = pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"attn_implementation": "eager"}
)

pipe_sdpa = pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"attn_implementation": "sdpa"}
)

long_text = "FlashAttention is a fast and memory-efficient exact attention algorithm. " * 1000 #改大一點試試看
print(f"輸入長度： {len(long_text)} 字元\n")

print(f"== 測試 Attention Implementation: Naive Attention ==")

print("正在進行 Warmup...")
pipe_eager("Hello", max_new_tokens=1)

print("開始測試...")
start_time = time.time()

pipe_eager(long_text, max_new_tokens=1)

torch.cuda.synchronize()

end_time = time.time()
latency = end_time - start_time
print(f"耗時： {latency:.4f} 秒")

# 清理記憶體
torch.cuda.empty_cache()

print(f"== 測試 Attention Implementation: Flash Attention ==")

print("正在進行 Warmup...")
pipe_sdpa("Hello", max_new_tokens=1)

print("開始測試...")
start_time = time.time()

pipe_sdpa(long_text, max_new_tokens=1)

torch.cuda.synchronize()

end_time = time.time()
latency = end_time - start_time
print(f"耗時： {latency:.4f} 秒")

# 清理記憶體
torch.cuda.empty_cache()